#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

ulimit -s unlimited

setup_dirs
use_solution sl.cpp opt

compile gen_random.py
compile gen_cyclic.py
compile gen_absurd.py

samplegroup
limits n=20
sample 1
sample 2
sample 3

group group1 25
limits n=100 r=10
tc small-rand1 gen_random n=10 k=10
tc small-rand2 gen_random n=100 k=100 r=10 exact=1
tc small-rand3 gen_random n=100 k=40 r=10
tc small-rand4 gen_random n=100 k=10
tc small-cyclic1 gen_cyclic n=100 k=2 count=20 r=1 padding=20
tc small-cyclic2 gen_cyclic n=100 k=40 r=10 padding=10
tc small-full gen_random n=100 k=10 full=1
tc small-imp1 gen_random n=100 k=100 r=10 imp=1
tc small-imp2 gen_absurd n=100 k=50 r=10

group group2 25
limits n=4000 r=10
include_group group1
tc medium-rand1 gen_random n=4000 k=4000 r=10
tc medium-rand2 gen_random n=4000 k=1600 r=10
tc medium-rand3 gen_random n=4000 k=10 r=10 exact=1
tc medium-cyclic1 gen_cyclic n=4000 k=2 count=800 r=1 padding=800
tc medium-cyclic2 gen_cyclic n=4000 k=11 count=220 r=10
tc medium-cyclic3 gen_cyclic n=4000 k=2500 r=10 padding=400

group group3 25
limits n=200000 r=10
include_group group2
tc large-rand1 gen_random n=200000 k=200000 r=10
tc large-rand2 gen_random n=200000 k=8000 r=10
tc large-rand3 gen_random n=200000 k=10 r=10 exact=1
tc large-cyclic1 gen_cyclic n=200000 k=10 count=10000 r=9
tc large-cyclic2 gen_cyclic n=200000 k=2 count=40000 r=1 padding=40000
tc large-cyclic3 gen_cyclic n=200000 k=11 count=10 r=10 padding=40000
tc large-cyclic4 gen_cyclic n=200000 k=11 count=6000 r=10 padding=20000
tc large-cyclic5 gen_cyclic n=200000 k=80000 r=10 padding=20000
tc large-full gen_random n=200000 k=10 full=1
tc large-imp gen_random n=200000 k=100 r=10 imp=1

group group4 25
limits n=200000
include_group group3
tc full-rand1 gen_random n=200000 k=180000 exact=1
tc full-rand2 gen_random n=200000 k=8000
tc full-rand3 gen_random n=200000 k=20000 r=16000
tc full-cyclic1 gen_cyclic n=200000 k=80000
tc full-cyclic2 gen_cyclic n=200000 k=60000 padding=20000
tc full-cyclic3 gen_cyclic n=200000 k=60000 r=20000 padding=20000
tc full-cyclic4 gen_cyclic n=200000 k=2 padding=20000
tc full-imp gen_absurd n=200000 k=100000 r=80000

cleanup_programs
