#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

ulimit -s unlimited

setup_dirs
use_solution sol.cpp

# TODO: smarter generators...
compile gen_random.py

samplegroup
limits n=20
# sample 1

group group1 25
limits n=20
tc small-1 gen_random n=20
tc small-2 gen_random n=20 mode=perm

group group2 25
limits n=1e5 special=all_loved
tc perm-1 gen_random n=10 mode=perm
tc perm-2 gen_random n=100000 mode=perm

group group3 25
limits n=1e5 special=no_cycles
tc ego-1 gen_random n=10 mode=ego
tc ego-2 gen_random n=100000 mode=ego

group group4 25
limits n=1e5
include_group group1
include_group group2
include_group group3
tc large-1 gen_random n=100000

cleanup_programs
