#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

ulimit -s unlimited

setup_dirs
use_solution sol.cpp

compile gen_random.py
compile handmade.py

samplegroup
limits n=20
sample 1
sample 2
sample 3

group group1 21
limits n=20
tc small-handmade handmade
tc small-tiny1 gen_random n=2
tc small-tiny2 gen_random n=4
tc small-tiny3 gen_random n=6
tc small-tiny4 gen_random n=8
tc small-rand1 gen_random n=20
tc small-rand2 gen_random n=20
tc small-rand3 gen_random n=20
tc small-rand4 gen_random n=20
tc small-perm gen_random n=20 mode=perm
tc small-ego1 gen_random n=20 mode=ego,line,1
tc small-ego2 gen_random n=20 mode=ego,star,1
tc small-ego3 gen_random n=20 mode=ego,random,1
tc small-imp1 gen_random n=3
tc small-imp2 gen_random n=19

group group2 25
limits n=1e5 special=all_loved
tc perm-1 gen_random n=2 mode=perm
tc perm-2 gen_random n=4 mode=perm
tc perm-3 gen_random n=6 mode=perm
tc perm-4 gen_random n=100000 mode=perm
tc perm-5 gen_random n=100000 mode=many-cycles
tc perm-6 gen_random n=100000 mode=one-cycle
tc perm-imp gen_random n=99999 mode=perm

group group3 29
limits n=1e5 special=no_cycles
tc ego-ego     gen_random n=100000 mode=ego,random,100000
tc ego-tiny1   gen_random n=16     mode=ego,random,1
tc ego-tiny2   gen_random n=10     mode=ego,random,2
tc ego-tiny3   gen_random n=10     mode=ego,random,3
tc ego-tiny4   gen_random n=16     mode=ego,random,3
tc ego-rand1   gen_random n=100000 mode=ego,random,1
tc ego-rand2   gen_random n=100000 mode=ego,random,1000
tc ego-rand3   gen_random n=100000 mode=ego,random,50000
tc ego-star    gen_random n=100000 mode=ego,star,1
tc ego-line    gen_random n=100000 mode=ego,line,2
tc ego-shallow gen_random n=100000 mode=ego,shallow,3
tc ego-deep    gen_random n=100000 mode=ego,deep,1000
tc ego-deeper  gen_random n=100000 mode=ego,deeper,1
tc ego-imp     gen_random n=99999  mode=ego,random,511

group group4 25
# order large cases before the other ones
limits n=1e5
include_group group1
include_group group2
include_group group3
tc alarge-deeper  gen_random n=100000 mode=general,deeper,1000,perm
tc alarge-grand1  gen_random n=100000 mode=general,random,30000,perm
tc alarge-grand2  gen_random n=100000 mode=general,random,30000,many-cycles
tc alarge-grand3  gen_random n=100000 mode=general,random,100,perm
tc alarge-grand4  gen_random n=100000 mode=general,random,100,many-cycles
tc alarge-rand1   gen_random n=100000
tc alarge-rand2   gen_random n=100000
tc alarge-rand3   gen_random n=100000
tc alarge-rand4   gen_random n=100000
tc alarge-rand5   gen_random n=100000
tc alarge-shallow gen_random n=100000 mode=general,shallow,1000,perm

cleanup_programs
