#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

ulimit -s unlimited

setup_dirs
use_solution sol.cpp

# TODO: smarter generators...
compile gen_random.py
compile handmade.py

samplegroup
limits n=20
sample 1
sample 2

group group1 25
limits n=20
tc small-1 handmade
for i in {2..5}; do
    tc small-$i gen_random n=$i
    done
for i in {6..10}; do
    tc small-$i gen_random n=20
    done

group group2 25
limits n=1e5 special=all_loved
for i in {1..5}; do
    tc perm-$i gen_random n=1$i mode=perm
    done
for i in {6..9}; do
    tc perm-$i gen_random n=100000 mode=perm
    done
tc perm-10 gen_random n=100000 mode=loops

group group3 25
limits n=1e5 special=no_cycles
tc ego-1     gen_random n=15     m=1 mode=random
tc ego-2     gen_random n=100000 m=1 mode=random
tc ego-3     gen_random n=100000 m=1000 mode=random
tc star-1    gen_random n=100000 m=1 mode=star
tc star-2    gen_random n=100000 m=1000 mode=star
tc line-1    gen_random n=100000 m=1 mode=line
tc line-2    gen_random n=100000 m=1000 mode=line
tc shallow-1 gen_random n=100000 m=1 mode=shallow
tc shallow-2 gen_random n=100000 m=1000 mode=shallow
tc deep-1    gen_random n=100000 m=1 mode=deep
tc deep-2    gen_random n=100000 m=1000 mode=deep
tc deeper-1  gen_random n=100000 m=1 mode=deeper
tc deeper-2  gen_random n=100000 m=1000 mode=deeper

group group4 25
limits n=1e5
include_group group1
include_group group2
include_group group3
for i in {1..5}; do
    tc large-$i gen_random n=100000
    done

cleanup_programs
