#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

ulimit -s unlimited

setup_dirs
use_solution sl.cpp

compile gen_random.py
compile gen_star.py
compile gen_halfstar.py
compile gen_doublestar.py
compile gen_manycomponents.py

samplegroup
limits n=20
sample 1

group group1 25
limits n=100 k=4
tc tiny-1 gen_random n=2 m=1 k=4
tc tiny-2 gen_random n=3 m=3 k=3
tc small-2 gen_random n=30 m=100 k=4
tc small-3 gen_random n=100 m=100 k=4
tc small-4 gen_random n=50 m=100 k=3
tc small-5 gen_random n=50 m=100 k=2
tc small-6 gen_random n=50 m=100 k=1
tc small-7 gen_star n=100 k=4 extra=1
tc small-8 gen_halfstar n=60 extra=40
tc small-9 gen_manycomponents n=100 m=100 k=4 compsize=5

group group2 25
limits n=3e5 k=3
tc k3-1 gen_random n=5000 m=300000 k=3
tc k3-2 gen_random n=800 m=300000 k=3
tc k3-3 gen_random n=300000 m=300000 k=3
tc k3-4 gen_random n=30000 m=300000 k=2
tc k3-5 gen_random n=30000 m=300000 k=1
tc k3-6 gen_star n=200000 k=3 extra=100000
tc k3-7 gen_manycomponents n=300000 m=300000 k=3 compsize=400
tc k3-8 gen_manycomponents n=300000 m=300000 k=3 compsize=4

group group3 25
limits n=3e5 k=4
include_group group1
include_group group2
tc k4-1 gen_random n=800 m=300000 k=4
tc k4-2 gen_random n=8000 m=300000 k=4
tc k4-3 gen_random n=300000 m=300000 k=4
tc k4-4 gen_star n=150000 k=4 extra=150000
tc k4-5 gen_halfstar n=150000 extra=150000
tc k4-6 gen_manycomponents n=300000 m=300000 k=4 compsize=450

group group4 25
limits n=1e5 k=5
include_group group1
tc k5-1 gen_random n=2 m=1 k=5
tc k5-2 gen_random n=480 m=100000 k=5
tc k5-3 gen_random n=100000 m=100000 k=5
tc k5-4 gen_star n=50000 k=5 extra=40000
tc k5-5 gen_doublestar n=75000
tc k5-6 gen_doublestar n=50000 extra=30000
tc k5-7 gen_manycomponents n=100000 m=100000 k=5 compsize=300
tc k5-8 gen_manycomponents n=100000 m=100000 k=5 compsize=6
tc k5-3-1 gen_random n=480 m=100000 k=3
tc k5-3-2 gen_random n=100000 m=100000 k=3
tc k5-3-3 gen_star n=100000 k=3
tc k5-4-1 gen_random n=480 m=100000 k=4
tc k5-4-2 gen_random n=100000 m=100000 k=4
tc k5-4-3 gen_star n=100000 k=4
tc k5-4-4 gen_halfstar n=100000

cleanup_programs
