#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

setup_dirs
use_solution ../../data/empty.sh # empty .ans files

compile echo.sh

samplegroup

LIMS=''
params() {
	limits $1 $2 $3 $4
	LIMS="$1 $2 $3 $4"
}

group group1 10
params 1000000 1 1 10000
tc 1d1-const echo $LIMS const
tc 1d1-corner1 echo $LIMS corner +++
tc 1d1-corner2 echo $LIMS corner ---
tc 1d1-peak echo $LIMS 1d-peak 0
tc 1d1-random echo $LIMS random

group group2 20
params 1000000 1 1 35
tc 1d2-blocks echo $LIMS 1d-block
tc 1d2-const echo $LIMS const
tc 1d2-corner1 echo $LIMS corner +++
tc 1d2-corner2 echo $LIMS corner ---
tc 1d2-peak1 echo $LIMS 1d-peak 0
tc 1d2-peak2 echo $LIMS 1d-peak 1
tc 1d2-peak3 echo $LIMS 1d-peak 0
tc 1d2-peak4 echo $LIMS 1d-peak 1
tc 1d2-peak5 echo $LIMS 1d-peak2 sqrt
tc 1d2-peak6 echo $LIMS 1d-peak2 pw
tc 1d2-random echo $LIMS random

group group3 10
params 200 200 1 4000
tc 2d1-const echo $LIMS const
tc 2d1-corner echo $LIMS corner +++
tc 2d1-random echo $LIMS random
tc 2d1-space echo $LIMS pspaced spacefill
tc 2d1-spiral echo $LIMS pspaced spiral

group group4 10
params 1000 1000 1 4000
tc 2d2-const echo $LIMS const
tc 2d2-corner echo $LIMS corner +-+
tc 2d2-random echo $LIMS random
tc 2d2-space1 echo $LIMS pspaced spacefill
tc 2d2-space2 echo $LIMS pad 15 3 0 10 20 0 spaced spacefill
tc 2d2-spiral echo $LIMS pspaced spiral

group group5 20
params 100 100 100 100000
tc 3d1-const echo $LIMS const
tc 3d1-corner echo $LIMS corner ++-
tc 3d1-random echo $LIMS random
tc 3d1-space echo $LIMS pspaced spacefill
tc 3d1-walk echo $LIMS walk 0.3 300

group group6 30
params 500 500 500 150000
tc 3d2-const echo $LIMS const
tc 3d2-corner echo $LIMS corner -+-
tc 3d2-random echo $LIMS random
tc 3d2-space1 echo $LIMS pspaced spacefill
tc 3d2-space2 echo $LIMS pspaced spacefill
tc 3d2-space3 echo $LIMS pad 29 9 19 10 20 20 spaced spacefill
tc 3d2-walk1 echo $LIMS walk 0.3 500 # path len ~ 350'000, 0.3s
tc 3d2-walk2 echo $LIMS walk 0.03 1000 # path len ~ 480'000, 0.3s
tc 3d2-walk3 echo $LIMS walk 0.1 1000 # path len ~ 540'000, 0.4s
tc 3d2-walk4 echo $LIMS walk 0.6 700 # path len ~ 660'000, 0.7s

# 4d?
# group 1: dims = 30, q = 100'000
# group 2: dims = 70, q = 100'000

cleanup_programs
